sudo: required
dist: precise64
language: node_js
node_js:
- '8'
before_install:
- sudo apt-get update
services:
- mongodb
install:
- npm install
- npm -g install casperjs
- npm -g install phantomjs
- npm -g install mocha
- npm -g install chai
before_script:
- npm start &
- sleep 5
script:
- npm run test
- npm run casperTest
branches:
  only:
  - master
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
deploy:
  provider: heroku
  api_key:
    secure: JzTEfeQzhAcFVm9hHep60+dutuVRhVA5NfN6SYlBe2vpfvIA+qhQa1FqabvxqccXFZOX/ceyzcHhyCICJxB+UUJr/J/wiJL1Eogyiuact4nmqC3pauGr+grSiGMeooXF7TNhDcvI90YJE+TLVGsJCiAPxLSTeiVfUIKNPa0Y+UWKUKgKk143BBtUB6ApKI3Jeu2i0xTpuNvWUgQr1o3LGy9VqEL+Nyq1W2lkcRav63GyE8Ym1rZjyUz5K6l+fJ3PfvyTBrPd4iJVO0xUP3vKuO49jBh8A3s9+f923OFTb62mM0fsje7uCkjEEcp75ZKJYnX2/5R9tIZ9O9qLMp9xpSU9D0SEgYBz/fIGja2UsCynLLUfqTYAsujRwYsfRhCr11rI6T2RNyymBpT8g1AiRJyuWHsFSsqmjGiHZTT0Tg50OFrKYCjehZw5+UBeZkNmGGJN0ScKI7174qqvNM900WWdPBafl4Qu/7RXS7DgbcuD5JtsuYm4wgTDNfruIGvk/26zJnJN+VIvczCp23hL47Y/uki+Nljk7eWRTT4f19uqeG3A6WvmXG+OZC5hYWfr5sD02Pb7okPi8SDiui0B7VWa4UDzQ+arb+y/5M/ZFJfvmqsDML169dNYW2ln1Mc5pEsb8OZoz0cGqr0YqHAd8CiLxzZSjcawaENLYdj+VOI=
  app: todo-list-aschhabra
  on: master
