sudo: required
dist: precise64
language: node_js
node_js:
- '8'
before_install:
- sudo apt-get update
services:
- mongodb
install:
- npm install
- npm -g install casperjs
- npm -g install phantomjs
- npm -g install mocha
- npm -g install chai
before_script:
- npm start &
- sleep 5
script:
- npm run test
- npm run casperTest
branches:
  only:
  - master
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
deploy:
  provider: heroku
  api_key:
    secure: ep6mJNlylJcJJXfLdmeSRBKVy0lUu2l3oMj42PzGv11jkL737aaNAzpjP6Ox8RagRII16SlGIQgPUIKgwJsQ3FzuCOW7eUEx187AfR/LaGEZZclSEOhYOrT2snYfv4rNPc313+TMogvnNS06752daBBIuz6GT4oUe+4tZHT4c2zakziAmLH3wEuaTAOfZHszPkSbaIN9C0A1iuo4fcs9QgFxoamc1dwhPL7ax0PWcDWcdcNLCqpfWBahkMUHOfGybGfc+KCGuKXfh0xc1g9TiHma8E01tn6ClVdxAdyybta+K32W4krU4/ZKpb33edPF8mCQoCzNy7YqopXv65Df8SvXdYmdNNg4J8U2iOlA94nzYC3nxjvCKQZVHJKAVzWZYxxii2lfyJdbpdtPM6/EPvf5fO+jHljWsZw40+CIVKxZG8RNfor2RHj+UlB//C24zxv5GRNUKI+GImiNmJAXa2FzBS90i/7+Dvk+uKefPpDaiYVtQxQFE7cVNMm01ddxS2JNnhWLDRr9X+yIvK4J7hWmhadKHmKrP7S4FsWYJVuSNdyO4UksDuzZ0efIW+eVVpEjeWkg+FzaE3R1eMEimWl0QU73jRsaRfrkVto1bp/MCw982fPUfUBtyyNerOCoyV267k3k4+PpePlCCwVM4qot4BAkaocZ2pETqCm56mg=
  app: todo-list-aschhabra
  on: master
